# Generated by Django 4.1.7 on 2023-03-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_trucks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='free_trucks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_num', models.IntegerField()),
            ],
        ),
    ]
