# Generated by Django 4.1.7 on 2023-04-18 10:22

from django.db import migrations, models
import package.models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='eta',
            field=models.DateField(default=package.models.five_days_from_now),
        ),
        migrations.AddField(
            model_name='package',
            name='status',
            field=models.CharField(default='Received', max_length=50),
        ),
    ]
