# Generated by Django 4.1.7 on 2023-03-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='subject_name',
            field=models.CharField(max_length=128),
        ),
    ]
