# Generated by Django 4.1.7 on 2023-03-20 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='password',
            field=models.CharField(default='password', max_length=56),
        ),
    ]
